from tkinter import *
from tkinter import ttk
root = Tk()
root.title("Address entry form")
root.geometry('500x350')
a = Label(root,text = "First name")
a.grid(row = 0,column = 0)
b = Label(root,text = "last name:")
b.grid(row = 1,column = 0)
c = Label(root,text = "Address line 1:")
c.grid(row = 2,column = 0)
d = Label(root,text = "Address line 2:")
d.grid(row = 3,column = 0)
e = Label(root,text = "City:")
e.grid(row = 4,column = 0)
f = Label(root,text = "State:")
f.grid(row = 5,column = 0)
g = Label(root,text = "Postal code:")
g.grid(row = 6,column = 0)
h = Label(root,text = "Country:")
h.grid(row = 7,column = 0)
a1 = Entry(root,width=30)
a1.grid(row = 0,column = 1)
b1 = Entry(root,width=30)
b1.grid(row = 1,column = 1)
c1 = Entry(root,width=30)
c1.grid(row = 2,column = 1)
d1 = Entry(root,width=30)
d1.grid(row = 3,column = 1)
e1 = Entry(root,width=30)
e1.grid(row = 4,column = 1)
f1 = Entry(root,width=30)
f1.grid(row = 5,column = 1)
g1 = Entry(root,width=30)
g1.grid(row = 6,column = 1)
h1 = Entry(root,width=30)
h1.grid(row = 7,column = 1)
def clear_text():
    a1.delete(0,END)
    b1.delete(0,END)
    c1.delete(0,END)
    d1.delete(0,END)
    e1.delete(0,END)
    f1.delete(0,END)
    g1.delete(0,END)
    h1.delete(0,END)
Sub = ttk.Button(root,text = "Submit").grid(row = 8,column = 0)
clr = ttk.Button(root, text = "Clear",command = clear_text).grid(row = 8,column = 1)
root.mainloop()